name: rl-game
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - matplotlib==3.2.0
  - seaborn
  - pygame==2.0.0
  - gym==0.12.0
  - pip:
      tensorflow==2.4.1
      scikit-image==0.19.0
      numpy==1.19.5